datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: jdbc:h2:mem:app
  production:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

ebean:
  ddl:
    generate: true
    run: true